package co.edu.ucompensar.loanbooks.Views;

import co.edu.ucompensar.loanbooks.Controller.PostLoansBDBooks;
import co.edu.ucompensar.loanbooks.Models.Client;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Angie Melo
 */
public class Clientes extends javax.swing.JFrame {

    PostLoansBDBooks clientCrud = new PostLoansBDBooks();
    int selectRow = -1;
    
    /**
     * Creates new form Libros
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientsList = new javax.swing.JTable();
        jButtonSearch = new javax.swing.JButton();
        jTextClientSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextClientDocument = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextClientName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextClientLastname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jComboBoxClientStatus = new javax.swing.JComboBox<>();
        loadData = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setText("Categoria");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        jTableClientsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idCliente", "Documento", "Nombres", "Apellidos", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableClientsList);

        jButtonSearch.setText("Consultar");
        jButtonSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jTextClientSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextClientSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese el documento del cliente que desea consultar");

        jLabel6.setText("Documento:");

        jTextClientDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextClientDocumentActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombres:");

        jTextClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextClientNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellidos:");

        jTextClientLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextClientLastnameActionPerformed(evt);
            }
        });

        jLabel7.setText("Estado");

        jButtonSave.setText("Insertar");
        jButtonSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Editar");
        jButtonEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Eliminar");
        jButtonDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jComboBoxClientStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Activo", "Inactivo", "Suspendido" }));

        loadData.setText("Cargar Datos");
        loadData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDataActionPerformed(evt);
            }
        });

        escritorio.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jButtonSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jTextClientSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jTextClientDocument, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jTextClientName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jTextClientLastname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jButtonSave, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jButtonEdit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jButtonDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jComboBoxClientStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(loadData, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addComponent(jTextClientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextClientName)
                            .addComponent(jTextClientDocument)
                            .addComponent(jTextClientLastname)
                            .addComponent(jComboBoxClientStatus, 0, 192, Short.MAX_VALUE))
                        .addGap(63, 63, 63))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addComponent(loadData, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextClientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jTextClientDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextClientLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxClientStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loadData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(2, 64, 89));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextClientDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextClientDocumentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextClientDocumentActionPerformed

    private void jTextClientSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextClientSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextClientSearchActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        String search = jTextClientSearch.getText();
        ArrayList<Client> clientList = new ArrayList<>(); 
        
        if(search.isEmpty()){
            clientList = clientCrud.getClients();
        }else{
            clientList = clientCrud.getClient(Long.parseLong(search));
        }       
        
        
        String[][] dataTable = new String[clientList.size()][5];
        
        for (int i = 0; i < clientList.size(); i++) {
            dataTable[i][0] = String.valueOf(clientList.get(i).getIdClient());
            dataTable[i][1] = String.valueOf(clientList.get(i).getDocument());
            dataTable[i][2] = clientList.get(i).getName();
            dataTable[i][3] = clientList.get(i).getLastName();
            dataTable[i][4] = clientList.get(i).getStatus();
        }
        
        jTableClientsList.setModel(new javax.swing.table.DefaultTableModel(
            dataTable,new String [] {
                "Id Cliente", "Documento", "Nombre", "Apellido", "Estado"
            }
        ));          
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTextClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextClientNameActionPerformed

    private void jTextClientLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextClientLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextClientLastnameActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try{
            long clientDocument = Long.parseLong(this.jTextClientDocument.getText());
            String clientName  = this.jTextClientName.getText();
            String clientLastname = this.jTextClientLastname.getText();
            String clientStatus = this.jComboBoxClientStatus.getSelectedItem().toString();

            if(clientDocument != 0){
                if(!clientName.isEmpty()){
                    if(!clientLastname.isEmpty()){
                        if(clientStatus != "Seleccione"){
                            Client client = new Client(clientDocument,clientName,clientLastname,clientStatus);                
                            clientCrud.insertClients(client);
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "El valor de campo Estado es invalido","Error",0);
                        }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "El valor de campo Apellido es invalido","Error",0);
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "El valor de campo Nombre es invalido","Error",0);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "El valor de campo documento es invalido","Error",0);
            }

            
            
        }catch(NumberFormatException efn){
            JOptionPane.showMessageDialog(rootPane, "El Documento no debe de estar vacio y debe ser numerico","Error",0);
        }
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        selectRow = this.jTableClientsList.getSelectedRow();
        int clientDocument,id;
        String clientName,clientLastname,clientStatus,idClient;
                
        if(this.jTableClientsList.getSelectedRow() != -1){
            
            clientDocument = Integer.parseInt(this.jTextClientDocument.getText());
            clientName  = this.jTextClientName.getText();
            clientLastname = this.jTextClientLastname.getText();
            clientStatus = this.jComboBoxClientStatus.getSelectedItem().toString();
            
            if(clientDocument != 0){
                if(!clientName.isEmpty()){
                    if(!clientLastname.isEmpty()){
                        if(clientStatus != "Seleccione"){
                            idClient = (String) jTableClientsList.getValueAt(selectRow, 0);                        
                            id = Integer.parseInt(idClient);            
                            Client client = new Client(id, clientDocument, clientName, clientLastname, clientStatus);
                            clientCrud.updateClients(client);
                            this.clean();
                         }else{
                            JOptionPane.showMessageDialog(rootPane, "El valor de campo Estado es invalido","Error",0);
                        }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "El valor de campo Apellido es invalido","Error",0);
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "El valor de campo Nombre es invalido","Error",0);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "El valor de campo documento es invalido","Error",0);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un elemento de la tabla");
        }
        
        
        
    }//GEN-LAST:event_jButtonEditActionPerformed

    
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        selectRow = this.jTableClientsList.getSelectedRow();
        int id;
        String idClient;
        if(this.jTableClientsList.getSelectedRow() != -1){            
            idClient = (String) jTableClientsList.getValueAt(selectRow, 0);
            id = Integer.parseInt(idClient);                        
            clientCrud.deleteClients(id);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un elemento de la tabla");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void loadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDataActionPerformed
        selectRow = this.jTableClientsList.getSelectedRow();
        if(selectRow != -1){
            this.jTextClientDocument.setText((String) jTableClientsList.getValueAt(selectRow, 1));
            this.jTextClientName.setText((String) jTableClientsList.getValueAt(selectRow, 2));
            this.jTextClientLastname.setText((String) jTableClientsList.getValueAt(selectRow, 3));        
            this.jComboBoxClientStatus.getModel().setSelectedItem(jTableClientsList.getValueAt(selectRow, 4));
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un elemento de la tabla");
        }
    }//GEN-LAST:event_loadDataActionPerformed
    
    public void clean(){
        this.jTextClientDocument.setText("");
        this.jTextClientName.setText("");
        this.jTextClientLastname.setText("");        
        this.jComboBoxClientStatus.setSelectedIndex(0);        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBoxClientStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientsList;
    private javax.swing.JTextField jTextClientDocument;
    private javax.swing.JTextField jTextClientLastname;
    private javax.swing.JTextField jTextClientName;
    private javax.swing.JTextField jTextClientSearch;
    private javax.swing.JButton loadData;
    // End of variables declaration//GEN-END:variables
}
